### ISSUE TITLE
jumpgate still referring to CCIManager (which was changed in SLAPI to VSmanager)

### ISSUE THREAD

**Issue by Neetuj** [softlayer/jumpgate#166]
~/office/jumpgate (master) > nova availability-zone-list
REQ: GET /v2.0  {} [ReqId: req-c05c26a4-a712-11e4-b12d-8851fb5174fe]
UNKNOWN PATH: GET /v2.0
RESP: GET /v2.0  501 Not Implemented [ReqId: req-c05c26a4-a712-11e4-b12d-8851fb5174fe]
"127.0.0.1 - - [28/Jan/2015:11:26:10] "GET /v2.0 HTTP/1.1" 501 95 "-" "python-keystoneclient"
No handlers could be found for logger "keystoneclient.auth.identity.generic.base"
REQ: POST /v2.0/tokens  {} [ReqId: req-c05d3f9e-a712-11e4-b12d-8851fb5174fe]
RESP: POST /v2.0/tokens  200 OK [ReqId: req-c05d3f9e-a712-11e4-b12d-8851fb5174fe]
"127.0.0.1 - - [28/Jan/2015:11:26:11] "POST /v2.0/tokens HTTP/1.1" 200 2207 "-" "python-keystoneclient"
REQ: GET /compute/v2/13193/os-availability-zone/detail  {'tenant_id': '13193'} [ReqId: req-c0993116-a712-11e4-b12d-8851fb5174fe]
Unexpected Error
Traceback (most recent call last):
  File "falcon/api.py", line 96, in falcon.api.API.**call** (falcon/api.c:1587)
    responder(req, resp, *_params)  # pragma: no cover
  File "falcon/api_helpers.py", line 262, in falcon.api_helpers._wrap_with_before.do_before (falcon/api_helpers.c:3525)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 262, in falcon.api_helpers._wrap_with_before.do_before (falcon/api_helpers.c:3525)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 262, in falcon.api_helpers._wrap_with_before.do_before (falcon/api_helpers.c:3525)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 262, in falcon.api_helpers._wrap_with_before.do_before (falcon/api_helpers.c:3525)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 262, in falcon.api_helpers._wrap_with_before.do_before (falcon/api_helpers.c:3525)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 262, in falcon.api_helpers._wrap_with_before.do_before (falcon/api_helpers.c:3525)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 281, in falcon.api_helpers._wrap_with_after.do_after (falcon/api_helpers.c:3920)
    responder(req, resp, *_kwargs)
  File "falcon/api_helpers.py", line 281, in falcon.api_helpers._wrap_with_after.do_after (falcon/api_helpers.c:3920)
    responder(req, resp, **kwargs)
  File "/home/neetu/office/jumpgate/jumpgate/compute/drivers/sl/availability_zones.py", line 10, in on_get
    cci = SoftLayer.VSManager(client)
AttributeError: 'module' object has no attribute 'CCIManager'
RESP: GET /compute/v2/13193/os-availability-zone/detail  500 Internal Server Error [ReqId: req-c0993116-a712-11e4-b12d-8851fb5174fe]
"127.0.0.1 - - [28/Jan/2015:11:26:11] "GET /compute/v2/13193/os-availability-zone/detail HTTP/1.1" 500 101 "-" "python-novaclient"
ERROR (ClientException): Service Unavailable (HTTP 500) (Request-ID: req-c0993116-a712-11e4-b12d-8851fb5174fe)

**Comment by Neetuj** [comment]
#167
