### ISSUE TITLE
ValueError: The URI template for this route conflicts with another route's template.

### ISSUE THREAD

**Issue by kbroughton** [softlayer/jumpgate#169]
Following the jumpgate getting started guide
I had to apt-get install gunicorn python-devel

After that I edited jumpgate.conf

admin_token = kbroughton3
secret_key = my_sl_api_key

```
./test_server.sh
2015-05-15 13:29:15 [17107] [INFO] Starting gunicorn 17.5
2015-05-15 13:29:15 [17107] [INFO] Listening at: http://127.0.0.1:5000 (17107)
2015-05-15 13:29:15 [17107] [INFO] Using worker: sync
2015-05-15 13:29:15 [17113] [INFO] Booting worker with pid: 17113
Importing hook module 'jumpgate.common.hooks.core'
Adding response hook '<function hook_format at 0x7f3405265cf8>'
Adding request hook '<function hook_set_uuid at 0x7f3405265d70>'
Importing hook module 'jumpgate.common.hooks.log'
Adding request hook '<function log_request at 0x7f3405265e60>'
Adding response hook '<function log_response at 0x7f3405265ed8>'
Importing hook module 'jumpgate.common.hooks.admin_token'
Adding request hook '<function admin_token at 0x7f3405265f50>'
Importing hook module 'jumpgate.common.hooks.auth_token'
Adding request hook '<function validate_token at 0x7f3405239488>'
Importing hook module 'jumpgate.common.hooks.sl.client'
Adding request hook '<function bind_client at 0x7f3405239938>'
Importing hook module 'jumpgate.common.hooks.log'
Loading endpoint /volume/v2/{tenant_id}/volumes
Loading endpoint /volume/v2/{tenant_id}/os-volumes
Loading endpoint /volume/v2/{tenant_id}/volumes/detail
Loading endpoint /volume/v1/{tenant_id}/types
Loading endpoint /volume/v1/{tenant_id}/volumes
Loading endpoint /volume/v1/{tenant_id}/volumes/{volume_id}
2015-05-15 13:29:15 [17113] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 33, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 373, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/root/git/jumpgate/jumpgate/wsgi.py", line 41, in make_api
    return app.make_api()
  File "/root/git/jumpgate/jumpgate/api.py", line 73, in make_api
    api.add_route('%s.json' % endpoint, handler)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/api.py", line 316, in add_route
    self._router.add_route(uri_template, method_map, resource)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 84, in add_route
    insert(self._roots)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 69, in insert
    raise ValueError('The URI template for this route '
ValueError: The URI template for this route conflicts with another route's template.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 33, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 373, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/root/git/jumpgate/jumpgate/wsgi.py", line 41, in make_api
    return app.make_api()
  File "/root/git/jumpgate/jumpgate/api.py", line 73, in make_api
    api.add_route('%s.json' % endpoint, handler)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/api.py", line 316, in add_route
    self._router.add_route(uri_template, method_map, resource)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 84, in add_route
    insert(self._roots)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 64, in insert
    insert(node.children, path_index)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.3.0rc2-py2.7.egg/falcon/routing/compiled.py", line 69, in insert
    raise ValueError('The URI template for this route '
ValueError: The URI template for this route conflicts with another route's template.
2015-05-15 13:29:15 [17113] [INFO] Worker exiting (pid: 17113)
2015-05-15 13:29:15 [17116] [INFO] Booting worker with pid: 17116
```

possibly related to?
https://github.com/falconry/falcon/issues/535

**Comment by syallapr** [comment]
Were you able to fix this ? Am facing the same issue!

**Comment by kbroughton** [comment]
nothing so far

**Comment by luckyvega** [comment]
I met this issue, too. Installing falcon with version 0.1.8 can solve this problem. It seems that jumpgate is not compatible with the newest falcon.
