### ISSUE TITLE
OSError [Error 29] Illegal seek when runing with Openstack

### ISSUE THREAD

**Issue by wpf710** [softlayer/jumpgate#170]
I do not have a softlayer env yet, so run jumpgate againt openstack to test somthing as below:

1 openstack devstack setup
2 git clone jumpgate
3 modify the etc/jumpgate.conf by changing all the 'drivers.sl' to 'drivers.openstack', and also the endpoints for openstack service.
4 run jumpgate with the ./test_server.sh and ,it listen on 8000 port
5 curl -i http://keystone.openstack.addr:5000/ ,  it's OK
6 curl -i http://127.0.0.1:8000/
it failed with 

REQ: GET /  {} [ReqId: req-78d0d834-01e4-11e5-9743-000c29667376]
RESP: GET /  300 Multiple Choices [ReqId: req-78d0d834-01e4-11e5-9743-000c29667376]
2015-05-24 00:14:09 [99598] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 134, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 341, in write_file
    fd_offset = os.lseek(fileno, 0, os.SEEK_CUR)
OSError: [Errno 29] Illegal seek

what's wrong ？

**Comment by wpf710** [comment]
and with debugging , the jumpgate.common.openstack._standard_responder() had already get the  content and status code from openstack keystone.
